### ISSUE TITLE
Issues after sleep

### ISSUE THREAD

**Issue by Swimming33** [jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh#1]
After exiting sleep mode on my X2100, the OS will exhibit multiple issues relating to the graphics, such as improper text-rendering, image artifacting, youtube and other hardware-accelerated tasks failing to work, and sometimes a total black screen. My x2100 is a different configuration though, being an i7-10710u and the 3000x2000 screen (and I imagine that the difference in display has something to do with the issues).

**Comment by jamesfawcett** [comment]
Hi @Swimming33 my x2100 is currently in bits, I am awaiting delivery of a new ribbon because I am upgrading to the 3000x2000 LP130QP1-SPA1 LPM130M364 display. I've had it working, but I accidentally connected the FFC ribbon the wrong way round and burnt out one of the channels. Luckily the motherboard is still OK.

I will let you know if sleep still works ok when it arrives. To be honest though, sleep can be a bit hit and miss. Sometimes the keyboard will not work on resume. I tend to just "show the lockscreen" instead, and then the machine naturally falls asleep.

On my X330, using most of the EFI [from here ](https://github.com/banhbaoxamlan/X230-Hackintosh) sleep works great. I am going to look into that EFI to compare differences. It's on my list to do :)

**Comment by fotile96** [comment]
@jamesfawcett Hello, I am facing an issue that my x2100 (an i7-10710 ver.) cannot wake after sleep. After resetting the keyboard does not work until it boots into Windows or Hackintosh. Could you let me know the BIOS version you are using? I think the issue may be BIOS/EC related, though I am not sure.

**Comment by fotile96** [comment]
Get sleep and wake work by flashing the latest BIOS on https://www.xyte.ch/support/51nb-x210-x2100-software-support/x2100-x210-bios-ec/. :)

**Comment by jamesfawcett** [comment]
> Get sleep and wake work by flashing the latest BIOS on https://www.xyte.ch/support/51nb-x210-x2100-software-support/x2100-x210-bios-ec/. :)

Hi did that solve it? Sleep works 90% of the time for me.

If the keyboard doesn't work after reboot, the fix is to remove battery and put back in.

Has the bios update fully solved this for you?

**Comment by jamesfawcett** [comment]
Hi @fotile96 , all sleep issues are resolved for me now with the USB map I just added. I've been using this laptop full time on Mac OS now for all my work, every day as a web developer. No issues at all :)

**Comment by jamesfawcett** [comment]
@Swimming33 I have a 3000x2000 display for mine, I'll be fitting it soon so I'll test the difference.

**Comment by Swimming33** [comment]
Well... this is embarrassing. Turns out, the issue seems to of been related to the Intel ME integration on the X2100, and how it's sh*t. Luckily, I finally got around to actually soldering in the resistor and fixing it and um... yeah sleep works now.

So um... marking this as solved. Sorry for any inconvenience lol

**Comment by jamesfawcett** [comment]
That's great news! I've still not recieved my 3000x2000 display from Jacky yet, and I used my 2880 x 1920 to fix up an X210 I currently have on ebay https://www.ebay.co.uk/itm/275188300285 

Thanks for confirming it works for you with the 3000x2000 display! :) 

I am currently using my backup Hackintosh, a basic old i7 X201 but it's pretty quick with these mods: https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore
