### ISSUE TITLE
Sleep dont work

### ISSUE THREAD

**Issue by itayg43** [jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh#3]
Hi,
First of all thanks for the hard work!
I have problem with sleep on my machine... maybe you have an idead?

<img width="881" alt="Screen Shot 2022-06-02 at 2 59 38" src="https://user-images.githubusercontent.com/93944494/171520586-c8f4ec23-bd1b-47de-bc00-cd8fb6b40496.png">

**Comment by jamesfawcett** [comment]
Hi @itayg43 

I'm actually having a few unpredictable results myself at the minute with the latest Monterey, I need to take another look.

I think it's to do with the USB mapping. The OpenCore docs have recently changed their recommendations, and now recommend using USBMap rather than Hackintool - I haven't had a 100% success rate yet: https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html 

![image](https://user-images.githubusercontent.com/5245272/171569158-9f68844a-2ae2-4542-bb42-a9b65301fe4f.png)

My current issue is that I can get sleep working with the above USBMap guide, but when the machine returns from sleep, it acts slow and unpredictable. Apps behave strange and freeze until I do a full reboot. I suspect it's something to do with Cputscsync here: https://github.com/acidanthera/bugtracker/issues/1676 

If you are interested in having a go, these are the ports here:

![x2100 usb ports](https://user-images.githubusercontent.com/5245272/171569636-f59f2cda-78eb-4ce5-b91d-0c972c16974e.png)

In USBMap, I set the "Internal" ports to 255, this wasn't specified in the guide on Github but those need to be internal for sleep to work.

I've been so busy with work lately I've not been able to have a proper look into this, but I did try the Cputscsync kext, but unfortunately didn't solve it straight away. 

I will dedicate some time to this soon, or if you have any ideas in the meantime please let me know! Otherwise, I will solve this as soon as I get time :)

**Comment by jamesfawcett** [comment]
Here are my notes from my progress with the USBPorts script: 

**Ports**
  UK10 = USBC both ways round
   UK04 = SD CARD
    UK06  Right front usb2 
    UK01 = USB2 
    UK02 = USB3

**Commands in the USBPort script:**    
       3,5,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26   9:10 
       0:1
        0:4  - (maybe wrong this is SD slot on the front)
        3:2 
        0:6

T:9:10 T:1,6:0 T:4:1 T:2:3
T:3,5,7,9,11,12,13,14,15,16,17,18:255  T:8:255 // Bluetooth

**Comment by jamesfawcett** [comment]
Hi @itayg43 

I've recreated the USB ports and its working for me again now. That USBMap tool wouldn't work for me, every time the left hand ports were all disabled. 

They're all working for me now with the latest file and sleep is working too, can you check?

[USBMap.kext.zip](https://github.com/jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh/files/8834248/USBMap.kext.zip)


thanks
James

**Comment by itayg43** [comment]
Hi James,
Thanks again, I'm new to this Hackintosh thing and I don't really understand too match from the usbmap part... I'm really sorry.
I tried the new usbmap kext and it also fixed the left-hand port problem for me. Screen brightness after restart/shutdown now stays the same and doesn't ramp up, but still, when I'm trying to go to sleep via the sleep button in the menu or the lock screen option as you offered the moonlight doesn't turn on, the screen turns black and never turn back on until hard shutdown via the on/off.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/93944494/171983239-f90b66bd-e307-40d9-9c5f-07814970f63d.png">
